language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kratafila/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kratafila/docker-react npm run test

